[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PulseProtect"
authors = [{name = "Shayan Vafaei", email = "shv.vafaei@gmail.com"}]
dynamic = ["version", "description"]
